version: "3.1"
services:
#apache
    www:
        container_name: www
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
volumes:
    persistent:
